[package]
name = "web-browser-engine"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.54", features = ["derive"] }
rustls = "0.23.36"
socket2 = "0.6.1"
webpki-roots = "1.0.5"
